# Generated by Django 3.0.3 on 2020-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion',
            name='player',
            field=models.CharField(default='No Name', max_length=30),
        ),
    ]
