# Generated by Django 3.0.3 on 2020-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0002_auto_20201014_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion',
            name='q1_option_one_select',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='firstquestion',
            name='q1_option_two_select',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
