# Generated by Django 3.0.3 on 2020-10-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0003_auto_20201014_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstQuestion_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField()),
                ('player', models.CharField(max_length=30)),
                ('q1_option_one_select', models.CharField(max_length=30)),
                ('q1_option_two_select', models.CharField(max_length=30)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplusers.matchFixture')),
            ],
        ),
    ]
