# Generated by Django 3.0.3 on 2020-10-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0004_firstquestion_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion_entry',
            name='q1_option_one_select',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='firstquestion_entry',
            name='q1_option_two_select',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
