# Generated by Django 3.0.3 on 2020-10-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0005_auto_20201015_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion_entry',
            name='match_id',
            field=models.IntegerField(default=0),
        ),
    ]
