# Generated by Django 3.0.3 on 2020-10-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0006_auto_20201015_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstquestion_entry',
            old_name='q1_option_one_select',
            new_name='q1_select',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q1_option_one_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q1_option_one_select',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q1_option_two_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q1_option_two_select',
        ),
        migrations.RemoveField(
            model_name='firstquestion_entry',
            name='q1_option_two_select',
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_answer', models.CharField(max_length=30)),
                ('q2_answer', models.CharField(max_length=30)),
                ('q3_answer', models.CharField(max_length=30)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplusers.matchFixture')),
            ],
        ),
    ]
