# Generated by Django 3.0.3 on 2020-10-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0009_auto_20201017_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstquestion',
            name='q1_one_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q1_two_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q2_four_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q2_one_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q2_three_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q2_two_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q3_four_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q3_one_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q3_three_count',
        ),
        migrations.RemoveField(
            model_name='firstquestion',
            name='q3_two_count',
        ),
    ]
