# Generated by Django 3.0.3 on 2020-10-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplusers', '0011_matchpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstquestion_entry',
            name='pred_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='firstquestion_entry',
            name='q1_flag',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='firstquestion_entry',
            name='q1_stake',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='firstquestion_entry',
            name='q2_flag',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='firstquestion_entry',
            name='q2_stake',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='firstquestion_entry',
            name='q3_flag',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='firstquestion_entry',
            name='q3_stake',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='firstquestion_entry',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
